### ISSUE TITLE
puNES v0.100 Compatibility Test

### ISSUE THREAD

**Issue by badgertapes** [punesemu/puNES#19]
today i decided to test all my roms in punes to see which ones worked and which ones didnt work. ive provided a list of games that were mostly compatible, and whether or not punes threw any errors upon loading.

NES Games
- 2-in-1 - Family Kid & Aladdin 4 (Ch) [!] - `Mapper 134 not supported, Illegal opcode 0x72 at 0x85EE`
- 6-in-1 (FK-3004)[p1][!] - `Works alright, but selecting "SONIC" or "HARRYPOTTER" will close the emulator.`
- 45-in-1 (JY-120A)(As) [U][!] - `Error loading rom.`
- 45-in-1 (Unl) (As) [f1] - `Compatible. puNES does not emulate DIP switches so 90-in-1 menu can't be accessed.`
- 260-in-1 [p1][!] - `Compatible. 210-in-1 menu, available when simply opening rom in FCEUX, can't be accessed.`
- 999999-in-1 (8 bit Slim Station, NEWPXP-DVT22-A PCB)(Unl)[U][!] - `Error loading rom. Dump from cah4e3 designed for compatibility with fceumm.`
- Aladdin (Super Game)(Unl)[!] - `This one is really irritating. Sometimes the game will work almost 100%, other times it crashes upon pressing start or waiting on the title screen. According to Nestopia Image Info, it is Mapper 114, SUPERGAME LIONKING.`
- Dr. Mario II (Unl)[U][!] - `Error loading rom. Another dump by cah4e3 for fceumm.`
- Duck Hunt (VS) - `VS System unsupported.`
- Kart Fighter (SOMARI-W) (Unl) [!] - `Illegal opcode 0x02 at 0x802E. SOMERITEAM SL-12, Mapper 116.`
- Lagrange Point (Japan) - `puNES VRC7 is at incorrect pitch. Game fine on other emulators.`
- Mappy Kids (Japan) - `puNES N163 does not support all channels. Game fine on other emulators.`
- Mr. Mary 2 (Unl) [!] - `Mapper 43 unsupported.`
- Q-Boy (Sachen) [U] [!] - `Error loading rom. UNL-Sachen-8259A, Mapper 141.`
- Somari (SOMARI-W) (Unl) [!] - `Illegal opcode 0x02 at 0x811A. SOMERITEAM SL-12, Mapper 116.`
- Sonic & Knuckles 5 (1997) (Unl) [!] - `Nothing wrong with the game itself, other than the act screen (SPRING YARD ZONE ACT 1) does not display after pressing start. Will display when using the level select code though.`
- Sonic 3D Blast 6 (Unl) - `Mapper 187 not supported. Illegal opcode 0x12 at 0xF51B.`
- Street Fighter II - The World Warrior (Unl) [!] - `Mapper 187 not supported. Illegal opcode 0x02 at 0x80D0.`
- Super 6-in-1 (KY-6011)[p1][!] - `"CRICKET WORLD CUP 2003" and "TURTLE FIGHTER IV" work good, but all other games have glitched graphics.`
- Super New Year Cart 15-in-1 (Hummer team) (Unl) [!] - `Works alright. Alternate menu choices, accessed by resetting in FCEUX, cannot be reached.`
- Toy Story (Unl) [!] - `Illegal opcode 0x02 at 0x0900. UNL A9746, Mapper 219.`

Those are all the games that have displayed errors or are mostly compatible. I hope you can look into these and try to get these fixed. Your emulator is excellent and I hope to see it improve!!

On an unrelated note, are there any chances of emulating the NTSC NES borders? Still hoping for maximized windows too! :>

**Comment by punesemu** [comment]
Thanks for the support.
In the personal WIP I have added support for the Vs System and with time I will add also the other mappers not supported.
What do you mean for NTSC NES borders?

**Comment by punesemu** [comment]
> Duck Hunt (VS) - VS System unsupported.

And one is done, [Vs. System support](https://github.com/punesemu/puNES/commit/8b47febd8050cf65f2525efa610fe4e47e01e69a).

**Comment by Famulator** [comment]
hi. sorry for not replying.
the ntsc nes borders are borders that use the background color when playing on ntsc tv. however it isnt important i suppose.

today i found out dip switches do work on punes, but they are used by soft reset. i suggest you should change it to be like nestopia, where you can select dip switches before game starts and change later on by menu.

i found out master fighter vi', which is an unlicensed game, doesnt work on punes. but im not sure what mapper it is.

**Comment by punesemu** [comment]
> 2-in-1 - Family Kid & Aladdin 4 (Ch) [!] - Mapper 134 not supported, Illegal opcode 0x72 at 0x85EE

https://github.com/punesemu/puNES/commit/0594494319e087e55c698e9151764de8d924958f
> 6-in-1 (FK-3004)[p1][!] - Works alright, but selecting "SONIC" or "HARRYPOTTER" will close the emulator.

https://github.com/punesemu/puNES/commit/4c919392551af7142b46bcd9ed5ef6794db3373c
> 45-in-1 (JY-120A)(As) [U][!] - Error loading rom.

https://github.com/punesemu/puNES/commit/c7ea9bb827f76a4afe68cad446f721583919cd10
> 45-in-1 (Unl) (As) [f1] - Compatible. puNES does not emulate DIP switches so 90-in-1 menu can't be accessed.

Press Soft Reset two times.
> Aladdin (Super Game)(Unl)[!] - This one is really irritating. Sometimes the game will work almost 100%, other times it crashes upon pressing start or waiting on the title screen. According to Nestopia Image Info, it is Mapper 114, SUPERGAME LIONKING. 

https://github.com/punesemu/puNES/commit/04bd24675964127c53adf4c967d639cf18c1f81e

**Comment by punesemu** [comment]
> Kart Fighter (SOMARI-W) (Unl) [!] - Illegal opcode 0x02 at 0x802E. SOMERITEAM SL-12, Mapper 116.
>Somari (SOMARI-W) (Unl) [!] - Illegal opcode 0x02 at 0x811A. SOMERITEAM SL-12, Mapper 116.

https://github.com/punesemu/puNES/commit/57dc5d18b0fcba737beb01c60c3f1717ef1bc567

**Comment by slacknk** [comment]
please add response/mapper for this game: [Nomolos: Storming the Catsle ](http://www.gradualgames.com/p/nomolos-storming-catsle.html)

**Comment by punesemu** [comment]
> please add response/mapper for this game: [Nomolos: Storming the Catsle ](http://www.gradualgames.com/p/nomolos-storming-catsle.html)
> Don't work opening history screen in game.

Fixed in https://github.com/punesemu/puNES/commit/d3a26238787292c26a60dbb0bbecfdc8f916ff67. Try last WIP.

**Comment by slacknk** [comment]
>> Nomolos: Storming the Catsle 

> Fixed in d3a2623. Try last WIP

works fine 31a490bc, thanks. Test on begin and end game

**Comment by anewuser** [comment]
@punesemu  The only ROM mentioned here that still doesn't seem to work is `Super New Year Cart 15-in-1 (Hummer Team) (Unl) [!]`. I can't get past the menus with the latest puNES WIP build.

**Comment by punesemu** [comment]
Fixed with 3a7b5fc.

**Comment by anewuser** [comment]
OP also mentioned sound issues with Lagrange Point and Mappy Kids, but they sound fine to me. If you double-check them, this issue can be closed now.

**Comment by punesemu** [comment]
Lagrange Point and Mappy Kids works right.
