### ISSUE TITLE
New NSFe Player: Some files don't play audio unless "Initial RAM value" set to 0x00

### ISSUE THREAD

**Issue by nelsonhef** [punesemu/puNES#380]
Hi!

During my tests, i found a couple of files that don't produce any sound in puNES 0.111 and later WIPs. They play fine in puNES 0.110.

- F-1 Sensation (Famicom NTSC): Outputs audio after setting "Initial RAM" to 0x00. Some tracks play incorrectly.
- Super Turrican (PAL): Outputs audio after setting "Initial RAM" to 0x00, but at NTSC speed. Plays OK after manually setting to PAL

[noaudio.zip](https://github.com/punesemu/puNES/files/14498365/noaudio.zip)

**Comment by punesemu** [comment]
Hi @nelsonhef, can you try the last WIP?

**Comment by nelsonhef** [comment]
Hi @punesemu, i've tested WIP 4df298d and the initialization and region setting is fixed (Super Turrican plays fine), but F-1 Sensation still have problems. It starts playing but as soon as the second song ends the thrird, instead of the actual song plays a part of the second one. Also, when in the first song, the "Next" button of the player doesn't go to the next song but rather other parts of the first song.

**Comment by punesemu** [comment]
Thx @nelsonhef, as soon as I finish implementing the 562 mapper I will dedicate myself to solving this bug. Thank you very much for your reports, they are very detailed and this makes my debugging sessions much easier.

**Comment by punesemu** [comment]
@nelsonhef can you try the last WIP? With the commit [8bf7379](https://github.com/punesemu/puNES/commit/8bf7379378df3625c245f44552d6e868c5cd7928) I fixed 2 bugs, one of which could be the cause of the strange behavior of F-1 Sensation.

**Comment by nelsonhef** [comment]
Hi @punesemu, i tested with the latest WIP 8bf7379 and unfortunately it doesn't solve the issue. But i noticed something. If I disable the playlist, the songs plays correctly at least until the end of the track list and then when it loops back to track 1 it starts playing wrong again. Another thing i hadn't noticed before was the track time/remaining time not updating correctly. I made two examples ilustrating the problem with the playlist on and off. Thank you for your efforts to fix these bugs and your kind words.


https://github.com/punesemu/puNES/assets/87081197/480905b2-6ad1-4052-a766-7e0ab23f260e


https://github.com/punesemu/puNES/assets/87081197/3fb80bce-31a5-4248-95a9-0eef162aa380

**Comment by punesemu** [comment]
Really strange, I can't reproduce the timer problem.

**Comment by nelsonhef** [comment]
@punesemu, i was able to find the condition that triggers the timers issue. To reproduce it, load the NSFE, hit the Stop button and then "Turn off/Hard Reset/Soft Reset" the emulator. The timers will stop working.

**Comment by punesemu** [comment]
Regarding the F-1 Sensation issue, can you try with the new WIP?

**Comment by punesemu** [comment]
And now I have also fixed the timers problem.

**Comment by nelsonhef** [comment]
Both issues were fixed in the latest WIP, thank you. Maybe i noticed another minor UI glitch. When you load a NSF file the "Fadeout" checkbox is selected and painted gray but if you Turn Off or Hard Reset the emulator it turns white.

**Comment by punesemu** [comment]
Thank you for your very thorough test, I will take a look at this issue as well.

**Comment by punesemu** [comment]
And with [74252de](https://github.com/punesemu/puNES/commit/74252dea3bae84e95303786fd32f3b34d70efe80) we should be done. :pray:

**Comment by nelsonhef** [comment]
Fixed. Thank you!
