### ISSUE TITLE
Frame Pacing issue

### ISSUE THREAD

**Issue by WizLizard** [punesemu/puNES#48]
puNES seems to have inconsistent frame pacing resulting in a not so smooth looking frame rate or what could be called a micro stutter. Nestopia does not suffer from this issue. Tested both the opengl and d3d builds. Maybe a true full screen mode could fix this? Either way it's not pleasant to people sensitive to this.

**Comment by punesemu** [comment]
You can try with the last WIP (https://github.com/punesemu/puNES/commit/d35e4e420e0f3cfd3cb9731f7ef0c38e04675fdb)? Make sure you have the Frameskip set to 0.

**Comment by WizLizard** [comment]
I always have framskip set to zero. I will try the latest WIP. How new is
it though, because i downloaded the latest a few weeks ago? I'm at work atm.

On Jul 10, 2017 5:03 PM, "Fabio Cavallo (FHorse)" <notifications@github.com>
wrote:

You can try with the last WIP (d35e4e4
<https://github.com/punesemu/puNES/commit/d35e4e420e0f3cfd3cb9731f7ef0c38e04675fdb>)?
Make sure you have the Frameskip set to 0.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/punesemu/puNES/issues/48#issuecomment-314241746>, or mute
the thread

**Comment by punesemu** [comment]
I made changes to the frameskip so I would like to test the new WIP I released a few hours ago.

**Comment by WizLizard** [comment]
Just tested it. Still get random micro stutters every so many frames. Tested on three of my windows 10 systems with Nvidia GPU's.

**Comment by punesemu** [comment]
Does the problem only occur in fullscreen mode?

**Comment by WizLizard** [comment]
Yes.

**Comment by WizLizard** [comment]
@punesemu Running the latest WIP with the windows fall update with frameskip at 0 and vsync on i'm no longer having this issue. However i'm having a new major issue. I will open a new issue for it.

**Comment by WizLizard** [comment]
@punesemu Ok i think this should be reopened as there is still an issue. Default frame skip = frame pacing/timing issue and frameskip 0 = no frame pacing/timing issue but audio randomly hitches. Someone in the forums also reported the audio hitching with frame skip set to 0.
